import { NextResponse } from "next/server";
import nodemailer from "nodemailer";

export async function POST(req) {
    try {
        const formdata = await req.formData();
        const companyName = formdata.get("company");
        const email = formdata.get("email");
        const url = formdata.get("url");
        const id = formdata.get("id");
        const transporter = nodemailer.createTransport({
            host: "smtp.hostinger.com",
            port: 465,
            secure: true,
            auth: {
                user: process.env.MAIL_USER,
                pass: process.env.MAIL_PASS,
            },
        });
        await transporter.sendMail({
            from: `"${companyName}" <invoice@vebedge.com>`,
            to: email,
            subject: `Invoice Number #${id}`,
            html: `
    <div style="font-family: Arial, Helvetica, sans-serif; background-color: #ffffff; padding: 30px; color: #000;">
      <p style="margin-bottom: 30px;">
        <a href="${url}" style="display: inline-block; padding: 12px 44px; background: #000; color: #fff; text-decoration: none; font-size: 15px; font-weight: bold;">
          View Invoice
        </a>
      </p>
      <p style="font-size: 13px; color: #555; margin-bottom: 20px;">
        Digital invoice generated by <strong>Veb Invoice</strong><br>
        Developed by <strong>Veb Edge</strong>.
      </p>
      <p style="font-size: 12px; color: #888;">
        © ${new Date().getFullYear()} Veb Invoice. All rights reserved.
      </p>
    </div>
            `
        });
        return NextResponse.json(200);
    } catch (error) {
        return NextResponse.json(400);
    }
}